apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- was.yaml
resources:
- was.yaml
images:
- name: cicd-image
  newName: hifrodo/rapa-cicdlab
  newTag: v9
namespace: default
